import {
  BuiltInPresetListSchema,
  type RadarPreset,
  type RadarPresetId,
} from "../types/presets";

const zeroAttributeOffsets = () => [
  { x: 0, y: 0 },
  { x: 0, y: 0 },
  { x: 0, y: 0 },
  { x: 0, y: 0 },
  { x: 0, y: 0 },
  { x: 0, y: 0 },
  { x: 0, y: 0 },
  { x: 0, y: 0 },
];

const parsedPresets = BuiltInPresetListSchema.parse([
  {
    id: "classic-indigo",
    page: {
      characterNameAlign: "center",
      theme: {
        backgroundColor: "#0a0a1a",
        gridColor: "rgba(255,255,255,0.12)",
        gridFillColor: "rgba(99,102,241,0.25)",
        gridStrokeColor: "rgba(99,102,241,0.8)",
        dotColor: "#818cf8",
        highValueDotColor: "#f59e0b",
        labelColor: "#e2e8f0",
        valueColor: "#f8fafc",
        glowColor: "#f59e0b",
        enhanceArrowColor: "#ef4444",
        weakenArrowColor: "#22c55e",
        silhouetteOpacity: 1,
        vignetteEnabled: true,
        vignetteBrightness: -30,
        vignetteCenterX: 50,
        vignetteCenterY: 50,
        vignetteInnerStop: 0,
        vignetteOuterStop: 100,
      },
      font: {
        characterName: 126,
        characterNameFamily: "Noto Sans SC",
        attributeLabel: 63,
        attributeLabelFamily: "Noto Sans SC",
        ratingLabel: 45,
        ratingLabelFamily: "Noto Sans SC",
        valuePopup: 54,
        valuePopupFamily: "Noto Sans SC",
      },
      layout: {
        radarCX: 1380,
        radarCY: 540,
        gridRingCount: 4,
        gridStrokeWidth: 1.5,
        silhouetteOffsetX: 0,
        silhouetteOffsetY: 0,
        silhouetteScale: 1,
        characterNameOffsetX: 0,
        characterNameOffsetY: 0,
        syncSilhouetteOffset: false,
        attributeLabelOffsetX: 0,
        attributeLabelOffsetY: 0,
        ratingLabelOffsetX: 0,
        ratingLabelOffsetY: 0,
        radarScale: 1,
      },
      attributeLabelOffsets: zeroAttributeOffsets(),
      slugStyle: {
        fontFamily: "Noto Sans SC",
        fontSize: 36,
        offsetX: 0,
        offsetY: 0,
        color: "#e2e8f0",
      },
      animationStyle: {
        valuePopupEnabled: true,
        valuePopupStyle: "spring",
        highValueGlowEnabled: true,
        highValueGlowStyle: "ring",
      },
    },
    comparison: {
      arrowStyle: {
        arrowFontSize: 45,
        arrowColor: "#94a3b8",
        arrowOffsetX: 0,
        arrowOffsetY: 0,
        diffFontSize: 45,
        diffEnhanceColor: "#ef4444",
        diffWeakenColor: "#22c55e",
        diffOffsetX: 0,
        diffOffsetY: 0,
      },
      transitionStyle: {
        polygonMode: "expand",
        showLegend: true,
        silhouetteSwapOffsetX: 80,
        silhouetteSwapOffsetY: 0,
        silhouetteFadeOutOpacity: 0.3,
        legendFontSize: 22,
        legendOffsetX: 0,
        legendOffsetY: 0,
        legendFontFamily: "",
        diffTriangleScale: 1,
        legendDotRadius: 6,
      },
      overlayStyle: {
        dimOpacity: 0.15,
        glowRadius: 16,
        arrowSize: 24,
        arrowSideOffset: 92,
        arrowOffsetY: 0,
        nameSideOffset: 665,
        silhouetteBaseOpacity: 0.4,
        silhouetteEmphasisOpacity: 0.85,
        silhouetteDimOpacity: 0.1,
      },
    },
  },
  {
    id: "brass-observatory",
    page: {
      characterNameAlign: "center",
      theme: {
        backgroundColor: "#17130D",
        gridColor: "rgba(217,164,65,0.16)",
        gridFillColor: "rgba(217,164,65,0.22)",
        gridStrokeColor: "rgba(217,164,65,0.82)",
        dotColor: "#F6D365",
        highValueDotColor: "#E8793E",
        labelColor: "#F4E7C5",
        valueColor: "#FFF8E7",
        glowColor: "#D9A441",
        enhanceArrowColor: "#E8793E",
        weakenArrowColor: "#62C6A8",
        silhouetteOpacity: 0.86,
        vignetteEnabled: true,
        vignetteBrightness: -36,
        vignetteCenterX: 32,
        vignetteCenterY: 50,
        vignetteInnerStop: 8,
        vignetteOuterStop: 100,
      },
      font: {
        characterName: 118,
        characterNameFamily: "Noto Serif SC",
        attributeLabel: 52,
        attributeLabelFamily: "Noto Serif SC",
        ratingLabel: 42,
        ratingLabelFamily: "Rajdhani",
        valuePopup: 48,
        valuePopupFamily: "Rajdhani",
      },
      layout: {
        radarCX: 1370,
        radarCY: 540,
        gridRingCount: 5,
        gridStrokeWidth: 1.4,
        silhouetteOffsetX: -15,
        silhouetteOffsetY: 0,
        silhouetteScale: 0.95,
        characterNameOffsetX: -18,
        characterNameOffsetY: 6,
        syncSilhouetteOffset: false,
        attributeLabelOffsetX: 0,
        attributeLabelOffsetY: 4,
        ratingLabelOffsetX: 0,
        ratingLabelOffsetY: 4,
        radarScale: 0.96,
      },
      attributeLabelOffsets: zeroAttributeOffsets(),
      slugStyle: {
        fontFamily: "Noto Serif SC",
        fontSize: 34,
        offsetX: -12,
        offsetY: 8,
        color: "#F4E7C5",
      },
      animationStyle: {
        valuePopupEnabled: true,
        valuePopupStyle: "fadeScale",
        highValueGlowEnabled: true,
        highValueGlowStyle: "pulse",
      },
    },
    comparison: {
      arrowStyle: {
        arrowFontSize: 40,
        arrowColor: "#D9A441",
        arrowOffsetX: 0,
        arrowOffsetY: 0,
        diffFontSize: 40,
        diffEnhanceColor: "#E8793E",
        diffWeakenColor: "#62C6A8",
        diffOffsetX: 0,
        diffOffsetY: 0,
      },
      transitionStyle: {
        polygonMode: "expand",
        showLegend: true,
        silhouetteSwapOffsetX: 72,
        silhouetteSwapOffsetY: 0,
        silhouetteFadeOutOpacity: 0.26,
        legendFontSize: 20,
        legendOffsetX: 0,
        legendOffsetY: 12,
        legendFontFamily: "Rajdhani",
        diffTriangleScale: 0.9,
        legendDotRadius: 5.5,
      },
      overlayStyle: {
        dimOpacity: 0.2,
        glowRadius: 10,
        arrowSize: 20,
        arrowSideOffset: 84,
        arrowOffsetY: 2,
        nameSideOffset: 650,
        silhouetteBaseOpacity: 0.34,
        silhouetteEmphasisOpacity: 0.76,
        silhouetteDimOpacity: 0.1,
      },
    },
  },
  {
    id: "mint-terminal",
    page: {
      characterNameAlign: "center",
      theme: {
        backgroundColor: "#041714",
        gridColor: "rgba(94,234,212,0.14)",
        gridFillColor: "rgba(94,234,212,0.20)",
        gridStrokeColor: "rgba(94,234,212,0.84)",
        dotColor: "#A7F3D0",
        highValueDotColor: "#D9F99D",
        labelColor: "#D1FAE5",
        valueColor: "#ECFDF5",
        glowColor: "#5EEAD4",
        enhanceArrowColor: "#FB7185",
        weakenArrowColor: "#A3E635",
        silhouetteOpacity: 0.84,
        vignetteEnabled: true,
        vignetteBrightness: -28,
        vignetteCenterX: 55,
        vignetteCenterY: 48,
        vignetteInnerStop: 0,
        vignetteOuterStop: 100,
      },
      font: {
        characterName: 122,
        characterNameFamily: "Exo 2",
        attributeLabel: 54,
        attributeLabelFamily: "Noto Sans SC",
        ratingLabel: 42,
        ratingLabelFamily: "Rajdhani",
        valuePopup: 50,
        valuePopupFamily: "Rajdhani",
      },
      layout: {
        radarCX: 1390,
        radarCY: 540,
        gridRingCount: 4,
        gridStrokeWidth: 1.25,
        silhouetteOffsetX: -10,
        silhouetteOffsetY: 0,
        silhouetteScale: 0.95,
        characterNameOffsetX: 0,
        characterNameOffsetY: -4,
        syncSilhouetteOffset: false,
        attributeLabelOffsetX: 6,
        attributeLabelOffsetY: 0,
        ratingLabelOffsetX: 4,
        ratingLabelOffsetY: 0,
        radarScale: 0.98,
      },
      attributeLabelOffsets: zeroAttributeOffsets(),
      slugStyle: {
        fontFamily: "Exo 2",
        fontSize: 32,
        offsetX: 0,
        offsetY: 8,
        color: "#A7F3D0",
      },
      animationStyle: {
        valuePopupEnabled: true,
        valuePopupStyle: "slideIn",
        highValueGlowEnabled: true,
        highValueGlowStyle: "ripple",
      },
    },
    comparison: {
      arrowStyle: {
        arrowFontSize: 42,
        arrowColor: "#5EEAD4",
        arrowOffsetX: 0,
        arrowOffsetY: 0,
        diffFontSize: 42,
        diffEnhanceColor: "#FB7185",
        diffWeakenColor: "#A3E635",
        diffOffsetX: 0,
        diffOffsetY: 0,
      },
      transitionStyle: {
        polygonMode: "extend",
        showLegend: true,
        silhouetteSwapOffsetX: 80,
        silhouetteSwapOffsetY: 0,
        silhouetteFadeOutOpacity: 0.22,
        legendFontSize: 20,
        legendOffsetX: 0,
        legendOffsetY: 4,
        legendFontFamily: "Rajdhani",
        diffTriangleScale: 1,
        legendDotRadius: 5,
      },
      overlayStyle: {
        dimOpacity: 0.16,
        glowRadius: 14,
        arrowSize: 22,
        arrowSideOffset: 88,
        arrowOffsetY: 0,
        nameSideOffset: 660,
        silhouetteBaseOpacity: 0.36,
        silhouetteEmphasisOpacity: 0.82,
        silhouetteDimOpacity: 0.08,
      },
    },
  },
  {
    id: "crimson-ringside",
    page: {
      characterNameAlign: "center",
      theme: {
        backgroundColor: "#17080C",
        gridColor: "rgba(252,165,165,0.14)",
        gridFillColor: "rgba(239,68,68,0.24)",
        gridStrokeColor: "rgba(239,68,68,0.88)",
        dotColor: "#FCA5A5",
        highValueDotColor: "#FB923C",
        labelColor: "#FFE4E6",
        valueColor: "#FFF1F2",
        glowColor: "#EF4444",
        enhanceArrowColor: "#FB923C",
        weakenArrowColor: "#34D399",
        silhouetteOpacity: 0.9,
        vignetteEnabled: true,
        vignetteBrightness: -34,
        vignetteCenterX: 45,
        vignetteCenterY: 50,
        vignetteInnerStop: 0,
        vignetteOuterStop: 100,
      },
      font: {
        characterName: 132,
        characterNameFamily: "ZCOOL KuaiLe",
        attributeLabel: 58,
        attributeLabelFamily: "Noto Sans SC",
        ratingLabel: 46,
        ratingLabelFamily: "Russo One",
        valuePopup: 54,
        valuePopupFamily: "Russo One",
      },
      layout: {
        radarCX: 1375,
        radarCY: 540,
        gridRingCount: 4,
        gridStrokeWidth: 2.2,
        silhouetteOffsetX: 0,
        silhouetteOffsetY: 8,
        silhouetteScale: 1.02,
        characterNameOffsetX: 0,
        characterNameOffsetY: -8,
        syncSilhouetteOffset: false,
        attributeLabelOffsetX: 0,
        attributeLabelOffsetY: 0,
        ratingLabelOffsetX: 0,
        ratingLabelOffsetY: 2,
        radarScale: 1.02,
      },
      attributeLabelOffsets: zeroAttributeOffsets(),
      slugStyle: {
        fontFamily: "ZCOOL KuaiLe",
        fontSize: 36,
        offsetX: 0,
        offsetY: 4,
        color: "#FFE4E6",
      },
      animationStyle: {
        valuePopupEnabled: true,
        valuePopupStyle: "bounce",
        highValueGlowEnabled: true,
        highValueGlowStyle: "ring",
      },
    },
    comparison: {
      arrowStyle: {
        arrowFontSize: 48,
        arrowColor: "#FCA5A5",
        arrowOffsetX: 0,
        arrowOffsetY: 0,
        diffFontSize: 48,
        diffEnhanceColor: "#FB923C",
        diffWeakenColor: "#34D399",
        diffOffsetX: 0,
        diffOffsetY: 0,
      },
      transitionStyle: {
        polygonMode: "extend",
        showLegend: true,
        silhouetteSwapOffsetX: 95,
        silhouetteSwapOffsetY: 0,
        silhouetteFadeOutOpacity: 0.28,
        legendFontSize: 24,
        legendOffsetX: 0,
        legendOffsetY: 4,
        legendFontFamily: "Russo One",
        diffTriangleScale: 1.15,
        legendDotRadius: 7,
      },
      overlayStyle: {
        dimOpacity: 0.14,
        glowRadius: 20,
        arrowSize: 26,
        arrowSideOffset: 100,
        arrowOffsetY: 0,
        nameSideOffset: 670,
        silhouetteBaseOpacity: 0.38,
        silhouetteEmphasisOpacity: 0.9,
        silhouetteDimOpacity: 0.08,
      },
    },
  },
  {
    id: "silver-cartography",
    page: {
      characterNameAlign: "center",
      theme: {
        backgroundColor: "#DCE7EA",
        gridColor: "rgba(30,41,59,0.18)",
        gridFillColor: "rgba(14,116,144,0.16)",
        gridStrokeColor: "rgba(14,116,144,0.82)",
        dotColor: "#155E75",
        highValueDotColor: "#C2410C",
        labelColor: "#1E293B",
        valueColor: "#020617",
        glowColor: "#0284C7",
        enhanceArrowColor: "#B91C1C",
        weakenArrowColor: "#047857",
        silhouetteOpacity: 0.7,
        vignetteEnabled: true,
        vignetteBrightness: -18,
        vignetteCenterX: 48,
        vignetteCenterY: 46,
        vignetteInnerStop: 12,
        vignetteOuterStop: 100,
      },
      font: {
        characterName: 116,
        characterNameFamily: "Noto Serif SC",
        attributeLabel: 50,
        attributeLabelFamily: "Noto Sans SC",
        ratingLabel: 40,
        ratingLabelFamily: "Rajdhani",
        valuePopup: 48,
        valuePopupFamily: "Rajdhani",
      },
      layout: {
        radarCX: 1370,
        radarCY: 540,
        gridRingCount: 5,
        gridStrokeWidth: 1.2,
        silhouetteOffsetX: -10,
        silhouetteOffsetY: 0,
        silhouetteScale: 0.92,
        characterNameOffsetX: -12,
        characterNameOffsetY: 0,
        syncSilhouetteOffset: false,
        attributeLabelOffsetX: 0,
        attributeLabelOffsetY: 0,
        ratingLabelOffsetX: 0,
        ratingLabelOffsetY: 4,
        radarScale: 0.94,
      },
      attributeLabelOffsets: zeroAttributeOffsets(),
      slugStyle: {
        fontFamily: "Noto Serif SC",
        fontSize: 32,
        offsetX: -8,
        offsetY: 8,
        color: "#1E293B",
      },
      animationStyle: {
        valuePopupEnabled: true,
        valuePopupStyle: "fadeScale",
        highValueGlowEnabled: true,
        highValueGlowStyle: "pulse",
      },
    },
    comparison: {
      arrowStyle: {
        arrowFontSize: 40,
        arrowColor: "#0E7490",
        arrowOffsetX: 0,
        arrowOffsetY: 0,
        diffFontSize: 40,
        diffEnhanceColor: "#B91C1C",
        diffWeakenColor: "#047857",
        diffOffsetX: 0,
        diffOffsetY: 0,
      },
      transitionStyle: {
        polygonMode: "expand",
        showLegend: true,
        silhouetteSwapOffsetX: 70,
        silhouetteSwapOffsetY: 0,
        silhouetteFadeOutOpacity: 0.38,
        legendFontSize: 20,
        legendOffsetX: 0,
        legendOffsetY: 8,
        legendFontFamily: "Rajdhani",
        diffTriangleScale: 0.85,
        legendDotRadius: 5,
      },
      overlayStyle: {
        dimOpacity: 0.28,
        glowRadius: 8,
        arrowSize: 20,
        arrowSideOffset: 84,
        arrowOffsetY: 0,
        nameSideOffset: 640,
        silhouetteBaseOpacity: 0.46,
        silhouetteEmphasisOpacity: 0.72,
        silhouetteDimOpacity: 0.18,
      },
    },
  },
]);

export const BUILT_IN_PRESETS: readonly RadarPreset[] =
  Object.freeze(parsedPresets);

export function getBuiltInPreset(id: RadarPresetId): RadarPreset {
  const preset = BUILT_IN_PRESETS.find((item) => item.id === id);
  if (!preset) {
    throw new Error(`Unknown built-in radar preset: ${id}`);
  }
  return preset;
}
